# Generated by Django 2.2.4 on 2019-08-09 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentmeta_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmeta',
            name='institute',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='verifytoken',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
