# Generated by Django 2.2.4 on 2019-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190809_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmeta',
            name='is_activemember',
            field=models.BooleanField(default=False),
        ),
    ]
