# Generated by Django 2.2.5 on 2019-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentmeta_is_activemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifytoken',
            name='token',
            field=models.CharField(max_length=32),
        ),
    ]
