# Generated by Django 2.2.5 on 2019-09-24 17:13

import datetime
from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    VerifyTokens = apps.get_model('students', 'VerifyToken')
    for token in VerifyTokens.objects.all():
        token.reminded = token.created
        token.save()

def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_confirmation_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifytoken',
            name='reminded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(set_my_defaults, reverse_func)
    ]
