# Generated by Django 2.2.4 on 2019-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='levelname',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
