# Generated by Django 2.2.4 on 2019-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_course_levelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.IntegerField(default=24),
        ),
    ]
