# Generated by Django 2.2.5 on 2019-09-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_course_limit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
