# Generated by Django 2.2.5 on 2019-09-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('levelname', models.CharField(blank=True, max_length=512, null=True)),
                ('limit', models.IntegerField(default=24)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.CourseType')),
            ],
        ),
    ]
