# Generated by Django 2.2.5 on 2019-09-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0005_course_coursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples_follower', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, 'manual'), (1, 'active member'), (2, 'student'), (3, 'lottery'), (4, 'else')])),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distribution.Couple')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distribution.Course')),
            ],
        ),
    ]
