# Generated by Django 2.2.5 on 2019-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_couple_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
    ]
