# Generated by Django 2.2.5 on 2019-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_distribution_admitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupledance',
            field=models.BooleanField(default=False),
        ),
    ]
