# Generated by Django 2.2.5 on 2019-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_course_coupledance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='reason',
            field=models.IntegerField(choices=[(0, 'manual'), (1, 'automatic')]),
        ),
    ]
