# Generated by Django 2.1.1 on 2018-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('student', models.BooleanField()),
                ('institute', models.IntegerField(choices=[(0, 'Eindhoven University of Technology'), (1, 'Fontys'), (2, 'Design Academy'), (4, 'Other'), (5, 'None')])),
                ('institute_other', models.CharField(blank=True, max_length=128, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('TN', 'Applied Physics'), ('BMT', 'Biomedical Engineering'), ('BE', 'Built Environment'), ('ST', 'Chemical Engineering and Chemistry'), ('ELE', 'Electrical Engineering'), ('ID', 'Industrial Design'), ('IE/IS', 'Industrial Engineering and Innovation Sciences'), ('W&I', 'Mathematics and Computer Science'), ('WTB', 'Mechanical Engineering')], max_length=5, null=True)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
