# Generated by Django 2.1.1 on 2018-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
